/*
 * generated by Xtext
 */
package org.xtext.example.umldsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.umldsl.services.UmlDslGrammarAccess;

public class UmlDslParser extends AbstractContentAssistParser {
	
	@Inject
	private UmlDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.umldsl.ui.contentassist.antlr.internal.InternalUmlDslParser createParser() {
		org.xtext.example.umldsl.ui.contentassist.antlr.internal.InternalUmlDslParser result = new org.xtext.example.umldsl.ui.contentassist.antlr.internal.InternalUmlDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getElementAccess().getGroup(), "rule__Element__Group__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getFooAccess().getGroup(), "rule__Foo__Group__0");
					put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
					put(grammarAccess.getElementAccess().getNameAssignment_1(), "rule__Element__NameAssignment_1");
					put(grammarAccess.getElementAccess().getRefAssignment_3(), "rule__Element__RefAssignment_3");
					put(grammarAccess.getFooAccess().getNameAssignment_1(), "rule__Foo__NameAssignment_1");
					put(grammarAccess.getFooAccess().getRefAssignment_3(), "rule__Foo__RefAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.umldsl.ui.contentassist.antlr.internal.InternalUmlDslParser typedParser = (org.xtext.example.umldsl.ui.contentassist.antlr.internal.InternalUmlDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public UmlDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmlDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
