package jetbrains.mps.tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptCalculator = new ConceptDescriptorBuilder("jetbrains.mps.tutorial.calculator.structure.Calculator", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1032eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.execution.util.structure.IMainClass", "jetbrains.mps.lang.core.structure.ScopeProvider").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L)).childDescriptors(new ConceptDescriptorBuilder.Link(5803879181371680129L, "inputField", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1a566L), true, true, false), new ConceptDescriptorBuilder.Link(5803879181371686934L, "outputField", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1bfeaL), true, true, false)).children(new String[]{"inputField", "outputField"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptInputField = new ConceptDescriptorBuilder("jetbrains.mps.tutorial.calculator.structure.InputField", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1a566L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = new ConceptDescriptorBuilder("jetbrains.mps.tutorial.calculator.structure.InputFieldReference", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1d61cL)).super_("jetbrains.mps.baseLanguage.structure.Expression").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(5803879181371692573L, "field", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1a566L), false)).references("field").create();
  /*package*/ final ConceptDescriptor myConceptOutputField = new ConceptDescriptorBuilder("jetbrains.mps.tutorial.calculator.structure.OutputField", MetaIdFactory.conceptId(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1bfeaL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(5803879181371689730L, "expression", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false)).children(new String[]{"expression"}, new boolean[]{false}).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0i, conceptFqName)) {
      case 0:
        return myConceptCalculator;
      case 1:
        return myConceptInputField;
      case 2:
        return myConceptInputFieldReference;
      case 3:
        return myConceptOutputField;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0i = new String[]{"jetbrains.mps.tutorial.calculator.structure.Calculator", "jetbrains.mps.tutorial.calculator.structure.InputField", "jetbrains.mps.tutorial.calculator.structure.InputFieldReference", "jetbrains.mps.tutorial.calculator.structure.OutputField"};
}
