package Shapes.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_5819430965453292793(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453290911(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453330607(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20aL, 0x22b1af4dfbafa23cL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453330884(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20aL, 0x22b1af4dfbafa23eL, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453331193(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20aL, 0x22b1af4dfbafa241L, "radius"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453367731(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20aL, 0x22b1af4dfbafa241L, "radius"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453333548(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20bL, 0x22b1af4dfbafa245L, "upperLeftX"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453333825(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20bL, 0x22b1af4dfbafa247L, "upperLeftY"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453334128(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20bL, 0x22b1af4dfbafa24aL, "size"));
  }
  public static Object propertyMacro_GetPropertyValue_5819430965453368443(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa20bL, 0x22b1af4dfbafa24aL, "size"));
  }
  public static Object referenceMacro_GetReferent_5819430965453331872(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa1d9L, 0x6576aa16ce4788fcL, "color")), MetaAdapterFactory.getReferenceLink(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x6576aa16ce466f80L, 0x50c2c5a162c1716bL, "color"));
  }
  public static Object referenceMacro_GetReferent_5819430965453449502(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa24eL, "Shapes.structure.Canvas")), "graphicParam");
  }
  public static Object referenceMacro_GetReferent_5819430965453368797(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa1d9L, 0x6576aa16ce4788fcL, "color")), MetaAdapterFactory.getReferenceLink(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x6576aa16ce466f80L, 0x50c2c5a162c1716bL, "color"));
  }
  public static Object referenceMacro_GetReferent_5819430965453456773(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa24eL, "Shapes.structure.Canvas")), "graphicParam");
  }
  public static Iterable<SNode> sourceNodesQuery_5819430965453328051(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xaad3913e39ff4395L, 0xb433d37bdde7e6acL, 0x22b1af4dfbafa24eL, 0x22b1af4dfbafa251L, "shapes"));
  }
}
