package jetbrains.mps.tutorial.calculator.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1032eL, "jetbrains.mps.tutorial.calculator.structure.Calculator"))) {
        return Collections.<ConceptEditor>singletonList(new Calculator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1a566L, "jetbrains.mps.tutorial.calculator.structure.InputField"))) {
        return Collections.<ConceptEditor>singletonList(new InputField_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1d61cL, "jetbrains.mps.tutorial.calculator.structure.InputFieldReference"))) {
        return Collections.<ConceptEditor>singletonList(new InputFieldReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x716828fdb45041a2L, 0xbe0522e064c9a43bL, 0x508b855d7cf1bfeaL, "jetbrains.mps.tutorial.calculator.structure.OutputField"))) {
        return Collections.<ConceptEditor>singletonList(new OutputField_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
