package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAttribute = new ConceptDescriptorBuilder("CSS.structure.Attribute", MetaIdFactory.conceptId(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04291140L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301065802251L, "name"), new ConceptDescriptorBuilder.Prop(4793786301065793857L, "value")).properties("name", "value").create();
  /*package*/ final ConceptDescriptor myConceptCSS = new ConceptDescriptorBuilder("CSS.structure.CSS", MetaIdFactory.conceptId(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04290f94L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301065826751L, "fileName")).properties("fileName").childDescriptors(new ConceptDescriptorBuilder.Link(4793786301065793429L, "element", MetaIdFactory.conceptId(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04290f97L), true, true, false)).children(new String[]{"element"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptSelector = new ConceptDescriptorBuilder("CSS.structure.Selector", MetaIdFactory.conceptId(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04290f97L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301065793854L, "name")).properties("name").childDescriptors(new ConceptDescriptorBuilder.Link(4793786301065793859L, "attribute", MetaIdFactory.conceptId(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04291140L), true, true, false)).children(new String[]{"attribute"}, new boolean[]{true}).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAttribute, myConceptCSS, myConceptSelector);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0h, conceptFqName)) {
      case 0:
        return myConceptAttribute;
      case 1:
        return myConceptCSS;
      case 2:
        return myConceptSelector;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0h = new String[]{"CSS.structure.Attribute", "CSS.structure.CSS", "CSS.structure.Selector"};
}
