/*
 * generated by Xtext
 */
package org.xtext.example.umldsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.umldsl.ui.internal.UmlDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UmlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UmlDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UmlDslActivator.getInstance().getInjector(UmlDslActivator.ORG_XTEXT_EXAMPLE_UMLDSL_UMLDSL);
	}
	
}
