package FormularCreator.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Form_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<!DOCTYPE html>");
    tgs.newLine();
    tgs.append("<html>");
    tgs.newLine();
    tgs.append("\t<head>");
    tgs.newLine();
    tgs.append("\t\t<meta charset=\"utf-8\">");
    tgs.newLine();
    tgs.append("\t\t<title>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    tgs.append("</title>");
    tgs.newLine();
    tgs.append("\t\t<link rel=\"stylesheet\" href=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x4286f33e042a15f4L, "css")));
    tgs.append("\">");
    tgs.newLine();
    tgs.append("<script language=\"javascript\" type=\"text/javascript\" src=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x21673afa62502d5L, "javascript")));
    tgs.append("\"></script>");
    tgs.newLine();
    tgs.append("\t</head>");
    tgs.newLine();
    tgs.append("\t<body>");
    tgs.newLine();
    tgs.append("\t\t<h1>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x4286f33e042bb3deL, "title")));
    tgs.append("</h1>");
    tgs.newLine();
    tgs.append("\t\t<form action=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x4286f33e04367a17L, "action")));
    tgs.append("\" method=\"post\" name=\"");
    tgs.append("formular");
    tgs.append("\">");
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x29a3324f4c6c43b1L, "element"))) {
      tgs.appendNode(item);
    }
    tgs.append("\t\t</form>");
    tgs.newLine();
    tgs.append("\t\t</body>");
    tgs.newLine();
    tgs.append("</html>");
  }
  public String getFilename(SNode node) {
    return SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L, 0x4286f33e042a15ebL, "formName"));
  }
}
