package FormularCreator.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Label_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<label");
    tgs.append(" class=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L, 0x4286f33e042d9cdaL, "className")));
    tgs.append("\"");
    tgs.append(">");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b924aL, 0x29a3324f4c6b924bL, "value")));
    tgs.append("</label>");
  }
}
