package jetbrains.mps.tutorial.calculator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class MyCalculation extends JFrame {

  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }
    public void removeUpdate(DocumentEvent p0) {
      update();
    }
    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };
  private JTextField inputField_a_0 = new JTextField();
  private JTextField inputField_b_0 = new JTextField();
  private JTextField outputField_a_0 = new JTextField();

  public MyCalculation() {
    setTitle("MyCalculation");
    setLayout(new GridLayout(0, 2));
    inputField_a_0.getDocument().addDocumentListener(listener);
    add(new JLabel("inputFeld nr1"));
    add(inputField_a_0);
    inputField_b_0.getDocument().addDocumentListener(listener);
    add(new JLabel("inputFeld nr2"));
    add(inputField_b_0);
    add(new JLabel("Output"));
    add(outputField_a_0);
    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public void update() {
    int i_a_0 = 0;
    int i_b_0 = 0;
    try {
      i_a_0 = Integer.parseInt(inputField_a_0.getText());
      i_b_0 = Integer.parseInt(inputField_b_0.getText());
    } catch (NumberFormatException e) {
    }
    outputField_a_0.setText("" + (i_a_0 * 2 + i_b_0 * 4));
  }
  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new MyCalculation();
      }
    });
  }
}
