/*
 * generated by Xtext
 */
package org.xtext.example.umldsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.umldsl.services.UmlDslGrammarAccess;

public class UmlDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UmlDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.umldsl.parser.antlr.internal.InternalUmlDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.umldsl.parser.antlr.internal.InternalUmlDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public UmlDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmlDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
