package CSS.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04291140L, "CSS.structure.Attribute"))) {
        return Collections.<ConceptEditor>singletonList(new Attribute_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04290f94L, "CSS.structure.CSS"))) {
        return Collections.<ConceptEditor>singletonList(new CSS_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe30462c3244a471fL, 0x85b50e12ef920590L, 0x4286f33e04290f97L, "CSS.structure.Selector"))) {
        return Collections.<ConceptEditor>singletonList(new Selector_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
