package jetbrains.mps.tutorial.calculator.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class InputFieldReference_Behavior {
}
