package FormularCreator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptButton = new ConceptDescriptorBuilder("FormularCreator.structure.Button", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x5cfaed392144beccL)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(6699928225294106317L, "text"), new ConceptDescriptorBuilder.Prop(150434835807394698L, "name")).properties("text", "name").alias("btn", "").create();
  /*package*/ final ConceptDescriptor myConceptCheckbox = new ConceptDescriptorBuilder("FormularCreator.structure.Checkbox", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e042bfc36L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).alias("chk", "").create();
  /*package*/ final ConceptDescriptor myConceptDropdownButton = new ConceptDescriptorBuilder("FormularCreator.structure.DropdownButton", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e042bfc37L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).childDescriptors(new ConceptDescriptorBuilder.Link(4793786301066202416L, "element", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e042f4d2dL), false, true, false)).children(new String[]{"element"}, new boolean[]{true}).alias("db", "").create();
  /*package*/ final ConceptDescriptor myConceptDropdownElement = new ConceptDescriptorBuilder("FormularCreator.structure.DropdownElement", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e042f4d2dL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301066202414L, "value")).properties("value").alias("be", "").create();
  /*package*/ final ConceptDescriptor myConceptForm = new ConceptDescriptorBuilder("FormularCreator.structure.Form", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x6c446b1f9ef2a1f8L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.execution.util.structure.IMainClass").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301065860587L, "formName"), new ConceptDescriptorBuilder.Prop(4793786301065966558L, "title"), new ConceptDescriptorBuilder.Prop(4793786301065860596L, "css"), new ConceptDescriptorBuilder.Prop(4793786301066672663L, "action"), new ConceptDescriptorBuilder.Prop(150434835807404757L, "javascript")).properties("formName", "title", "css", "action", "javascript").childDescriptors(new ConceptDescriptorBuilder.Link(3000297092924851121L, "element", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L), true, true, false), new ConceptDescriptorBuilder.Link(7632465800613567067L, "linebreak", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x69ebf73505e393d6L), true, true, false)).children(new String[]{"element", "linebreak"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptFormelement = new ConceptDescriptorBuilder("FormularCreator.structure.Formelement", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301066091738L, "className")).properties("className").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptInput = new ConceptDescriptorBuilder("FormularCreator.structure.Input", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x21673afa625a9a6L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(150434835807447463L, "type"), new ConceptDescriptorBuilder.Prop(150434835807447465L, "name"), new ConceptDescriptorBuilder.Prop(150434835807447468L, "value")).properties("type", "name", "value").alias("input", "").create();
  /*package*/ final ConceptDescriptor myConceptLabel = new ConceptDescriptorBuilder("FormularCreator.structure.Label", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b924aL)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(3000297092924805707L, "value")).properties("value").alias("lbl", "").create();
  /*package*/ final ConceptDescriptor myConceptLineBreak = new ConceptDescriptorBuilder("FormularCreator.structure.LineBreak", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x69ebf73505e393d6L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).alias("lb", "").create();
  /*package*/ final ConceptDescriptor myConceptLink = new ConceptDescriptorBuilder("FormularCreator.structure.Link", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e0428be36L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301065772602L, "name"), new ConceptDescriptorBuilder.Prop(4793786301065772604L, "url")).properties("name", "url").alias("link", "").create();
  /*package*/ final ConceptDescriptor myConceptRadioButton = new ConceptDescriptorBuilder("FormularCreator.structure.RadioButton", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e042bfc38L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301066342538L, "name")).properties("name").childDescriptors(new ConceptDescriptorBuilder.Link(4793786301066300404L, "element", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e0430cbf1L), false, true, false)).children(new String[]{"element"}, new boolean[]{true}).alias("rb", "").create();
  /*package*/ final ConceptDescriptor myConceptRadioElement = new ConceptDescriptorBuilder("FormularCreator.structure.RadioElement", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e0430cbf1L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301066333533L, "name"), new ConceptDescriptorBuilder.Prop(4793786301066300402L, "value"), new ConceptDescriptorBuilder.Prop(4793786301066378088L, "text")).properties("name", "value", "text").create();
  /*package*/ final ConceptDescriptor myConceptText = new ConceptDescriptorBuilder("FormularCreator.structure.Text", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x4286f33e04305896L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4793786301066270871L, "value")).properties("value").alias("txt", "").create();
  /*package*/ final ConceptDescriptor myConceptTextArea = new ConceptDescriptorBuilder("FormularCreator.structure.TextArea", MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9239L)).super_("FormularCreator.structure.Formelement").super_(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).parents("FormularCreator.structure.Formelement").parentIds(MetaIdFactory.conceptId(0x2b1b62680e374cddL, 0x974d919e2a59d10fL, 0x29a3324f4c6b9269L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(6699928225294097920L, "name"), new ConceptDescriptorBuilder.Prop(3000297092924805690L, "value")).properties("name", "value").alias("ta", "").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptButton, myConceptCheckbox, myConceptDropdownButton, myConceptDropdownElement, myConceptForm, myConceptFormelement, myConceptInput, myConceptLabel, myConceptLineBreak, myConceptLink, myConceptRadioButton, myConceptRadioElement, myConceptText, myConceptTextArea);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0s, conceptFqName)) {
      case 0:
        return myConceptButton;
      case 1:
        return myConceptCheckbox;
      case 2:
        return myConceptDropdownButton;
      case 3:
        return myConceptDropdownElement;
      case 4:
        return myConceptForm;
      case 5:
        return myConceptFormelement;
      case 6:
        return myConceptInput;
      case 7:
        return myConceptLabel;
      case 8:
        return myConceptLineBreak;
      case 9:
        return myConceptLink;
      case 10:
        return myConceptRadioButton;
      case 11:
        return myConceptRadioElement;
      case 12:
        return myConceptText;
      case 13:
        return myConceptTextArea;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0s = new String[]{"FormularCreator.structure.Button", "FormularCreator.structure.Checkbox", "FormularCreator.structure.DropdownButton", "FormularCreator.structure.DropdownElement", "FormularCreator.structure.Form", "FormularCreator.structure.Formelement", "FormularCreator.structure.Input", "FormularCreator.structure.Label", "FormularCreator.structure.LineBreak", "FormularCreator.structure.Link", "FormularCreator.structure.RadioButton", "FormularCreator.structure.RadioElement", "FormularCreator.structure.Text", "FormularCreator.structure.TextArea"};
}
